name: AWS Brand Checks

on:
  pull_request:
  workflow_dispatch:
 
jobs:
  style-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Enforce AWS Brand Attribute
        uses: errata-ai/vale-action@reviewdog
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          fail_on_error: true
          reporter: github-pr-check
          filter_mode: added
          files: latest/ug
          vale_flags: "--config brand.vale.ini"
        continue-on-error: true
